// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_Panel2(lv_event_t * e);
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel5;
void ui_event_Arc1(lv_event_t * e);
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Panel3;
void ui_event_Arc2(lv_event_t * e);
extern lv_obj_t * ui_Arc2;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Image2;
void ui_event_Spinner1(lv_event_t * e);
extern lv_obj_t * ui_Spinner1;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
void ui_event_Switch2(lv_event_t * e);
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label12;
void ui_event_Panel9(lv_event_t * e);
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Image6;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
void ui_event_Panel8(lv_event_t * e);
extern lv_obj_t * ui_Panel8;
void ui_event_Panel7(lv_event_t * e);
extern lv_obj_t * ui_Panel7;
void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_1875797769);    // assets\mosquito (1).png
LV_IMG_DECLARE(ui_img_fan_png);    // assets\fan.png
LV_IMG_DECLARE(ui_img_1772094659);    // assets\settings (1).png
LV_IMG_DECLARE(ui_img_power_png);    // assets\power.png
LV_IMG_DECLARE(ui_img_110774521);    // assets\location-exclamation.png
LV_IMG_DECLARE(ui_img_1102696345);    // assets\home (1).png

LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font24);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
