// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void TempStatus(lv_event_t * e)
{
	
}

void tempstatustext(lv_event_t * e)
{
	// Your code here
}

void humiditystatus(lv_event_t * e)
{
	// Your code here
}

void humiditystatustext(lv_event_t * e)
{
	// Your code here
}

void Fandisplay(lv_event_t * e)
{
	// Your code here
}

void AotoFan(lv_event_t * e)
{
	// Your code here
}

void ONFan(lv_event_t * e)
{
	// Your code here
}

void WarningClean(lv_event_t * e)
{
	// Your code here
}

void WarningFeed(lv_event_t * e)
{
	// Your code here
}

void sliderTemp(lv_event_t * e)
{
	// Your code here
}

void SliderHumidity(lv_event_t * e)
{
	// Your code here
}
