// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void TempStatus(lv_event_t * e);
void tempstatustext(lv_event_t * e);
void humiditystatus(lv_event_t * e);
void humiditystatustext(lv_event_t * e);
void FanDisplay(lv_event_t * e);
void AotoFan(lv_event_t * e);
void ONFan(lv_event_t * e);
void WarningClean(lv_event_t * e);
void WarningFeed(lv_event_t * e);
void sliderTemp(lv_event_t * e);
void SliderHumidity(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
