// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void TempStatus(lv_event_t * e);
void temptext(lv_event_t * e);
void humistatus(lv_event_t * e);
void humiditytext(lv_event_t * e);
void Aoto(lv_event_t * e);
void ON(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
