// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void TempStatus(lv_event_t * e)
{
	// Your code here
}

void temptext(lv_event_t * e)
{
	// Your code here
}

void humistatus(lv_event_t * e)
{
	// Your code here
}

void humiditytext(lv_event_t * e)
{
	// Your code here
}

void Aoto(lv_event_t * e)
{
	// Your code here
}

void ON(lv_event_t * e)
{
	// Your code here
}
